name: Stock Checker CI

on:
    schedule:
        - cron: "*/10 * * * *" # Run every 10 minutes
    workflow_dispatch:  # Allows manual runs

jobs:
    run-script:
        runs-on: unbuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run Stock Checker Script
              run: python stock_checker.py